# GitHub Action that uses Black to reformat Python code (if needed) when doing a git push.
# If all Python code in the repo is compliant with Black then this Action does nothing.
# Otherwise, Black is run and its changes are committed to the repo.
# https://github.com/cclauss/autoblack

name: Black
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: pip install black
      - name: black
        run: |
          black .;
          git config --global user.name github-actions || exit 0;
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com' || exit 0;
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY || exit 0;
          git commit -am "fixup! Format Python code with psf/black push" || exit 0;
          git push --force origin HEAD:$GITHUB_REF || exit 0;
