name: License Check

on:
  push:

jobs:
  license-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: run docker-compose
        run: |
          docker-compose up -d
      - name: init containers
        run: |
          docker-compose exec -T django poetry run python manage.py makemigrations;
          docker-compose exec -T django poetry run python manage.py makemigrations streamer;
          docker-compose exec -T django poetry run python manage.py migrate;
          docker-compose exec -T django poetry run python manage.py collectstatic --noinput;
      - name: check licenses
        run: >
          docker-compose exec -T django pip-licenses
          --with-system
          --allow-only="
            Apache Software License;
            BSD License;BSD;
            Freeware;
            GNU General Public License (GPL);
            GNU Lesser General Public License v3 or later (LGPLv3+);
            MIT License;
            MIT;
            Mozilla Public License 2.0 (MPL 2.0);
            Python Software Foundation License;
            Public Domain;
            UNKNOWN;
            Zope Public License;
            ISC License (ISCL);
            "
