name: license-check

on:
  push:
  pull_request:
    branches:
      - main
      - develop

jobs:
  license-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: run docker-compose
        run: |
          docker-compose up -d
      - name: init containers
        run: |
          docker-compose exec -T django poetry run python manage.py makemigrations
          docker-compose exec -T django poetry run python manage.py makemigrations streamer
          docker-compose exec -T django poetry run python manage.py migrate
          docker-compose exec -T django poetry run python manage.py collectstatic --noinput
      - name: init containers
        run: |
          docker-compose exec django poetry run pip-licenses --order=license --allow-only="Apache Software License;\
            Apache Software License;\
            BSD License;BSD;\
            Freeware\
            GNU General Public License (GPL);\
            GNU Lesser General Public License v3 or later (LGPLv3+)\
            MIT License; MIT;\
            Mozilla Public License 2.0 (MPL 2.0)\
            Python Software Foundation License\
            UNKNOWN\
            Zope Public License\
            "
