name: lizard

on:
  push:

jobs:
  lizard:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Lizard Runner
        uses: Uno-Takashi/Lizard-Runner@v3
        with:
          path: "./Django"
          language: "python"
          exclude: "tests.py"
