name: Django pytest

on:
  push:
    branches:    
      - main
  pull_request:
    branches:    
      - main
      - develop

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: run docker-compose
        run: |
          docker-compose up -d
          docker-compose exec django bash
      - name: init containers
        run: |
          poetry run python manage.py makemigrations
          django poetry run python manage.py makemigrations streamer
          django poetry run python manage.py migrate
          django poetry run python manage.py collectstatic --noinput
      - name: run pytest
        run: |
          poetry run pytest --cov --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./Django/coverage.xml
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true