name: Pytest

on:
  push:

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: run docker-compose
        run: |
          docker-compose up -d
      - name: init containers
        run: |
          docker-compose exec -T django poetry run python manage.py makemigrations;
          docker-compose exec -T django poetry run python manage.py makemigrations streamer;
          docker-compose exec -T django poetry run python manage.py migrate;
          docker-compose exec -T django poetry run python manage.py collectstatic --noinput;
      - name: run pytest
        run: |
          docker-compose exec -T django pytest --cov --cov-report=xml --workers auto
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./Django/coverage.xml
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
