name: Security

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "25 21 * * 5"

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: install bandit
        run: pip install bandit
      - name: Checkout
        uses: actions/checkout@v3
      - name: run bandit
        run: |
          bandit Django -r -o ./bandit.txt -f txt -c ./.github/bandit.yml
      - name: Archive bandit log
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: bandit-report
          path: ./bandit.txt
  pyt:
    runs-on: ubuntu-latest
    steps:
      - name: install utils
        run: |
          sudo apt-get update
          sudo apt-get install moreutils -y
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: install python-taint
        run: pip install python-taint
      - name: Checkout
        uses: actions/checkout@v3
      - name: run pyt
        run: |
          pyt -a D -o pyt.txt ./Django
      - name: Archive pyt log
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: pyt-report
          path: ./pyt.txt
  codeql-analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["python"]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Learn more about CodeQL language support at https://git.io/codeql-language-support

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.
          # queries: ./path/to/local/query, your-org/your-repo/queries@main

      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below)
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      # ℹ️ Command-line programs to run using the OS shell.
      # 📚 https://git.io/JvXDl

      # ✏️ If the Autobuild fails above, remove it and uncomment the following three lines
      #    and modify them (or add more) to build your code if your project
      #    uses a compiled language

      #- run: |
      #   make bootstrap
      #   make release

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
  trivy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: run docker-compose
        run: |
          docker-compose build
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "d-party-backend_django:latest"
          format: "table"
          severity: "MEDIUM,HIGH,CRITICAL"
          exit-code: "1"
          ignore-unfixed: true
