name: trivy

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "25 21 * * 5"

jobs:
  trivy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: run docker-compose
        run: |
          docker-compose build
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "d-party-backend_django:latest"
          format: "table"
          severity: "MEDIUM,HIGH,CRITICAL"
          exit-code: "1"
          ignore-unfixed: true
